
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tah
 */
public class SaveSourceView extends View {

    /**
     * Creates new form SaveSourceView
     */

    //non GUI initial variables
    Controller control;

    public SaveSourceView() {
		control = null;
		initComponents();
	}

    public SaveSourceView(Controller c) {
		control = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        addSourceButton = new javax.swing.JButton();
        viewCitButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        saveNewPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveNewField = new javax.swing.JTextField();
        saveNewButton = new javax.swing.JButton();
        noticeLabel = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        addSourceButton.setText("Add Sources");
        addSourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSourceButtonActionPerformed(evt);
            }
        });

        viewCitButton.setText("View Citations");
        viewCitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCitButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load File");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewCitButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnButton)
                            .addComponent(addSourceButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(quitButton)
                                .addComponent(loadButton)))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(returnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSourceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCitButton)
                .addGap(25, 25, 25)
                .addComponent(loadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addGap(58, 58, 58))
        );

        jLabel1.setText("Enter File Name:");

        saveNewField.setText("filename.txt");

        saveNewButton.setText("Save");
        saveNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
				try{
                saveNewButtonActionPerformed(evt);
				}
				catch(IOException ex)
				{
				}
            }
        });

        noticeLabel.setText("File saved!");
        noticeLabel.setVisible(false);

        javax.swing.GroupLayout saveNewPanelLayout = new javax.swing.GroupLayout(saveNewPanel);
        saveNewPanel.setLayout(saveNewPanelLayout);
        saveNewPanelLayout.setHorizontalGroup(
            saveNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveNewPanelLayout.createSequentialGroup()
                .addGroup(saveNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveNewPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93)
                        .addComponent(saveNewField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(saveNewPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(saveNewButton))
                    .addGroup(saveNewPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(noticeLabel)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        saveNewPanelLayout.setVerticalGroup(
            saveNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveNewPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(saveNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(saveNewField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(saveNewButton)
                .addGap(67, 67, 67)
                .addComponent(noticeLabel)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Save New File", saveNewPanel);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
				try{
                jFileChooser1ActionPerformed(evt);
				}
				catch (IOException ex)
				{
				}
            }
        });
        jFileChooser1.setApproveButtonText("Save");

        jTabbedPane1.addTab("Overwrite File", jFileChooser1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // will call the method that re-initializes main menu view
        //close this frame
        View mainMenuFrame = new MainMenuView(control);
		mainMenuFrame.setVisible(true);
		control.viewSwitch(mainMenuFrame);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void addSourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSourceButtonActionPerformed
        //calls method to initialize add sources view
        // close this frame
        View addSourceFrame = new AddSourceView(control);
		addSourceFrame.setVisible(true);
		control.viewSwitch(addSourceFrame);
        this.dispose();
    }//GEN-LAST:event_addSourceButtonActionPerformed

    private void viewCitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCitButtonActionPerformed
        // calls method to initialize view citations
        //close this frame
        View viewCitFrame = new ViewCitations(control);
		viewCitFrame.setVisible(true);
		control.viewSwitch(viewCitFrame);
        this.dispose();
    }//GEN-LAST:event_viewCitButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // calls method to initialize load file view
        //close this frame
        View loadFrame = new LoadSourceView(control);
		loadFrame.setVisible(true);
		control.viewSwitch(loadFrame);
        this.dispose();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //call to initialize quit view
        //close this frame
        View quitFrame = new QuitView(control);
		quitFrame.setVisible(true);
		control.viewSwitch(quitFrame);
        this.dispose();
    }//GEN-LAST:event_quitButtonActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException{//GEN-FIRST:event_jFileChooser1ActionPerformed
        // send file to model to overwrite
        File f = jFileChooser1.getSelectedFile();
        control.saveProject(f);

    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void saveNewButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException{//GEN-FIRST:event_saveNewButtonActionPerformed
        // call appropriate methods to save file and set as current use file
        String fileName = saveNewField.getText();
        File f = new File(fileName);
        control.saveProject(f);

        //enable notice
        noticeLabel.setVisible(true);
    }//GEN-LAST:event_saveNewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveSourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveSourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveSourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveSourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveSourceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveNewButton;
    private javax.swing.JButton addSourceButton;
    private javax.swing.JButton viewCitButton;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel saveNewPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField saveNewField;
    private javax.swing.JLabel noticeLabel;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables

//method for setting the value of the controller object
    public void setController(Controller in)
    {
        control = in;
    }
}
